### ISSUE TITLE
Force close on start

### ISSUE THREAD

**Issue by yath** [kghost/ics-openvpn#1]
I/ActivityManager(  211): START {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=info.kghost.android.openvpn/.VpnSettings} from pid 607
D/dalvikvm(  211): JIT code cache reset in 4 ms (1048356 bytes 2/0)
D/dalvikvm(  211): GC_FOR_ALLOC freed 1877K, 13% free 17328K/19847K, paused 86ms
I/ActivityManager(  211): Start proc info.kghost.android.openvpn for activity info.kghost.android.openvpn/.VpnSettings: pid=3420 uid=10155 gids={3003}
D/OpenGLRenderer(  607): Flushing caches (mode 1)
D/OpenGLRenderer(  607): Flushing caches (mode 0)
D/libEGL  ( 3420): loaded /vendor/lib/egl/libEGL_POWERVR_SGX540_120.so
D/libEGL  ( 3420): loaded /vendor/lib/egl/libGLESv1_CM_POWERVR_SGX540_120.so
D/libEGL  ( 3420): loaded /vendor/lib/egl/libGLESv2_POWERVR_SGX540_120.so
D/OpenGLRenderer( 3420): Enabling debug mode 0
D/dalvikvm( 3420): No JNI_OnLoad found in /system/lib/libjni_openvpn.so 0x413591f8, skipping init
I/Process (  211): Sending signal. PID: 3420 SIG: 3
I/dalvikvm( 3420): threadid=3: reacting to signal 3
I/dalvikvm( 3420): Wrote stack traces to '/data/anr/traces.txt'
I/ActivityManager(  211): Displayed info.kghost.android.openvpn/.VpnSettings: +896ms
D/AndroidRuntime( 3420): Shutting down VM
W/dalvikvm( 3420): threadid=1: thread exiting with uncaught exception (group=0x40a5b1f8)
E/AndroidRuntime( 3420): FATAL EXCEPTION: main
E/AndroidRuntime( 3420): android.app.SuperNotCalledException: Fragment ErrorMsgDialog{413ac598 #0} did not call through to super.onCreate()
E/AndroidRuntime( 3420):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:797)
E/AndroidRuntime( 3420):        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
E/AndroidRuntime( 3420):        at android.app.BackStackRecord.run(BackStackRecord.java:622)
E/AndroidRuntime( 3420):        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1382)
E/AndroidRuntime( 3420):        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:426)
E/AndroidRuntime( 3420):        at android.os.Handler.handleCallback(Handler.java:605)
E/AndroidRuntime( 3420):        at android.os.Handler.dispatchMessage(Handler.java:92)
E/AndroidRuntime( 3420):        at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime( 3420):        at android.app.ActivityThread.main(ActivityThread.java:4424)
E/AndroidRuntime( 3420):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 3420):        at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime( 3420):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
E/AndroidRuntime( 3420):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:554)
E/AndroidRuntime( 3420):        at dalvik.system.NativeStart.main(Native Method)
W/ActivityManager(  211):   Force finishing activity info.kghost.android.openvpn/.VpnSettings

**Comment by kghost** [comment]
Can you provide your device information? Hardware model and android version.

**Comment by yath** [comment]
GT-I9000 (galaxysmtd), recent CM nightly (built yesterday).

**Comment by yath** [comment]
https://github.com/yath/ics-openvpn/commit/ad71f55892cb5b330c9626df95df860e7224f86f FYI
