### ISSUE TITLE
split tunneling

### ISSUE THREAD

**Issue by SameerRathod** [kghost/ics-openvpn#2]
Pardon me to ask this question here 
Do this application support split tunneling ?
If you can help me with split tunneling that will be great for me I want to configure split tunnel for my application

**Comment by robertg** [comment]
While this app might not explicitly mention split tunnelling, it is possible through Android's VpnService, by 'protecting' specific sockets.

**Comment by SushantTnex** [comment]
I have compile and run OpenVPN code from this link [http://github.com/kghost/ics-openvpn](http://github.com/kghost/ics-openvpn)
It display the Dialog with "Can't install OpenVpn". Please help on this problem

**Comment by kghost** [comment]
The VPN service provided by Android SDK supports split tunneling.
